version: "3.7"
services:
  api:    
    build: 
      context: ./API
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - pgdb
    environment:
      - DATABASE_URL=postgres://testUser:testPassword@pgdb:5432/postgres
    restart: on-failure
    container_name: irondb_web
    command: ["./API/docker/wait-for-it.sh", "pgdb:5432", "--timeout=90", "--", "node", "./API/bin/www"]

  pgdb:
    build: './API/docker/postgres'
    container_name: postgres
    restart: always
    # image: postgres:11.0-alpine
    volumes:
      - ./API/model/db-init:/docker-entrypoint-initdb.d/
      - ./API/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'testUser'
      POSTGRES_PASSWORD: 'testPassword'
      POSTGRES_DB: 'postgres'
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -d postgres -U group16"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  client:
    build: ./client
    ports:
      - "8001:8000"
    depends_on:
      - api