version: "3.7"
services:

  api:
    build: 
      context: .
      dockerfile: ./API/docker/node/Dockerfile
    volumes:
      - ./API:/usr/app/api
      - /usr/app/api/node_modules
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - pgdb
    environment:
      - DATABASE_URL=postgres://root:password@pgdb:5432/postgres
    restart: on-failure
    container_name: irondb_web
    command: ["./docker/wait-for-it.sh", "pgdb:5432", "--timeout=90", "--", "node", "./bin/www"]

  pgdb:
    build: './API/docker/postgres'
    container_name: postgres
    restart: always
    # image: postgres:11.0-alpine
    volumes:
      - ./API/model/db-init:/docker-entrypoint-initdb.d/
      - ./API/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -d postgres -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  client:
    build: ./client
    ports:
      - "127.0.0.1:8001:8000"
    depends_on:
      - api
    volumes:
      - ./client:/usr/app/client
      - /usr/app/client/node_modules
