version: "3.7"
services:

  web:
     
    build: 
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - pgdb
    environment:
      - DATABASE_URL=postgres://jrasmus4:*Jjrsx122497j*@pgdb:5432/postgres
    restart: on-failure
    container_name: irondb_web
    command: ["./docker/wait-for-it.sh", "pgdb:5432", "--timeout=90", "--", "node", "./bin/www"]

  pgdb:
    build: './docker/postgres'
    container_name: postgres
    restart: always
    # image: postgres:11.0-alpine
    volumes:
      - ./model/db-init:/docker-entrypoint-initdb.d/
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'jrasmus4'
      POSTGRES_PASSWORD: '*Jjrsx122497j*'
      POSTGRES_DB: 'postgres'
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -d postgres -U group16"]
      interval: 10s
      timeout: 5s
      retries: 5
